import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ 
  subsets: ['latin'],
  display: 'swap',
  preload: true
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Resource hints for better performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* Font face declarations for immediate availability */}
        <style dangerouslySetInnerHTML={{
          __html: `
            @font-face {
              font-family: 'Arial';
              src: local('Arial'), local('ArialMT');
              font-display: swap;
              font-weight: normal;
            }
            @font-face {
              font-family: 'Arial Black';
              src: local('Arial Black'), local('Arial-Black');
              font-display: swap;
              font-weight: 900;
            }
            
            /* Critical CSS for logo to prevent any flash */
            .logo-svg, .small-logo-svg {
              opacity: 1 !important;
              visibility: visible !important;
            }
          `
        }} />
      </head>
      <body className="overflow-y-scroll" suppressHydrationWarning>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}